### ISSUE TITLE
Allow to reuse a neptune run

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ai/neptune-pytorch-lightning#3]
For me that was the most convenient way:
```python
logger = NeptuneLogger(base_namespace="sth")
logger._run_instance = neptune_run
```
Consider accepting `neptune_run` as an argument to NeptuneLogger. But otherwise, works great. I have been positively surprised by finding `base_namespace` - very useful in my case.

**Comment by Raalsky** [comment]
Yeah, good point. Actually every new integration has an ability to provide a Neptune run :wink:. Check for ex. https://github.com/neptune-ai/neptune-tensorflow-keras/
I think in case of Pytorch Lightning integration it will be included in a few next updates :wink:

**Comment by kamil-kaczmarek** [comment]
hey @wjaskowski 

Indeed, in the new version of the logger (we now work on it), we will add option to pass Run object to the logger.

Do you have more feedback / ideas to share? Happy to consider.

**Comment by wjaskowski** [comment]
Nothing more about the lightning integration.

**Comment by Raalsky** [comment]
@wjaskowski Check out our new Pytorch Lightning integration :wink: https://pytorch-lightning.readthedocs.io/en/latest/_modules/pytorch_lightning/loggers/neptune.html#NeptuneLogger there is `run` argument as a way to reuse `Run` objects :wink:.
