### ISSUE TITLE
Extreamly poor performance due to version checking

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ai/neptune-pytorch-lightning#4]
The NeptuneLogger has a very poor performance and I know exactly why.

The problem is how version is obtained by the NeptuneLogger. It is always downloaded from the server! (Btw. what does this `1234` do there?!)
```python
    def version(self) -> str:
        try:
            self.run.sync()
        except NeptuneOfflineModeFetchException:
            return 'offline-id-1234'
        return self.run['sys/id'].fetch()
```

At the same time, Pytorch Lightning on epoch end (in `get_progress_bar_dict`) does the following:
```python
if self.trainer.logger is not None and self.trainer.logger.version is not None:
```
And here you get. In my case, 2/3 of the time is spent in this method.

**Comment by Raalsky** [comment]
Thanks @wjaskowski for your report. Could you confirm that the issue is solved with latest version of `neptune-pytorch-lightning` -> `0.9.2`?
